### ISSUE TITLE
Python 3.12 not supported?

### ISSUE THREAD

**Issue by darkBuddha** [bundesAPI/deutschland#128]
Hi, just tried to install it, this happened:

```
Collecting Shapely<2.0.0,>=1.8.0 (from deutschland)
  Downloading Shapely-1.8.5.post1.tar.gz (200 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 kB 26.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/darkBuddha/.miniforge3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/darkBuddha/.miniforge3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/darkBuddha/.miniforge3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/home/darkBuddha/.miniforge3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/darkBuddha/.miniforge3/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-3ertz8bd/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-3ertz8bd/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-3ertz8bd/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Which Python versions are supported? Maybe it should be added to the README...

**Comment by wirthual** [comment]
Hi,

thanks for posting the issue. I can reproduce this on a clean install of Python3.12.

Our test currently run for Python 3.8 to 3.11, so I would consider this as suuported. Expanding to 3.12 would be great.

After a bit of research seems its due to some deprecation of the importlib. See [here](https://docs.python.org/3/whatsnew/3.12.html#importlib).

So I think we need to check if we can use `shapely>2.0` and since we rely on `onnxruntime` package and it does not support `3.12` this might become a blocker for now: https://github.com/microsoft/onnxruntime/issues/17842

**Comment by wirthual** [comment]
Added a section in the README about supported python versions. See this [commit](https://github.com/bundesAPI/deutschland/commit/ac71469beed61e58cd4ffeb4d3640de0ccd6d8f7)

**Comment by wirthual** [comment]
Hi,
We are using [poetry](https://python-poetry.org/) to manage the dependencies. 

However if you want to can install the [export plugin](https://github.com/python-poetry/poetry-plugin-export) and export the dependencies to a `requirements.txt` as described [here](https://python-poetry.org/docs/cli/#export) with:

```bash
poetry export -f requirements.txt --output requirements.txt
```
