### ISSUE TITLE
Problem mit Bundesanzeiger

### ISSUE THREAD

**Issue by pinsel21** [bundesAPI/deutschland#13]
Ich verwende Python3.9 in einem dockerimage und plane die bundesAPI in einem
headless Projekt zu verwenden. Aber die Bundesanzeiger API verwendet google-chrome,
kann man das umgehen?

-------------------------------------

```
ba = Bundesanzeiger()

====== WebDriver manager ======
====== WebDriver manager ======
/bin/sh: 1: google-chrome: not found
/bin/sh: 1: google-chrome-stable: not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/deutschland/bundesanzeiger/bundesanzeiger.py", line 46, in __init__
    self.driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)
  File "/usr/local/lib/python3.9/site-packages/webdriver_manager/chrome.py", line 25, in __init__
    self.driver = ChromeDriver(name=name,
  File "/usr/local/lib/python3.9/site-packages/webdriver_manager/driver.py", line 57, in __init__
    self.browser_version = chrome_version(chrome_type)
  File "/usr/local/lib/python3.9/site-packages/webdriver_manager/utils.py", line 155, in chrome_version
    raise ValueError(f'Could not get version for Chrome with this command: {cmd}')
ValueError: Could not get version for Chrome with this command: google-chrome --version || google-chrome-stable --version

```

**Comment by pinsel21** [comment]
Prima, das ist gelöst. 
Bin jetzt aber auf #8 Issue aufgelaufen. Schaue ich mir heute abend näher an.
