### ISSUE TITLE
UnboundLocalError: local variable 'parsed' referenced before assignment

### ISSUE THREAD

**Issue by zopyx** [bundesAPI/deutschland#2]
```
>>> de.fetch([48.51999, 9.07136], [48.51999, 9.07137])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ajung/src/deutschland/lib/python3.9/site-packages/deutschland/geo.py", line 81, in fetch
    return parsed
UnboundLocalError: local variable 'parsed' referenced before assignment
```

**Comment by LilithWittmann** [comment]
Fixed in e1416af72144fdc482b7b49ba1f3753098857a03
