### ISSUE TITLE
import of Bundesanzeiger and Handelsregister not working

### ISSUE THREAD

**Issue by mwunderlich** [bundesAPI/deutschland#31]
The import of Bundesanzeiger and Handelsregister is not working in a new install of the "deutschland" package. 

How to reproduce: 
- pip install Shapely
- pip install deutschland
- open python REPL
- Try to import: from deutschland import Bundesanzeiger

Expected result: 
- python modules should be imported

What I got instead: 
```
>>> from deutschland import Bundesanzeiger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Bundesanzeiger' from 'deutschland' (/opt/homebrew/Caskroom/miniforge/base/envs/py_de/lib/python3.9/site-packages/deutschland/__init__.py)
>>> from deutschland import Handelsregister
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Handelsregister' from 'deutschland' (/opt/homebrew/Caskroom/miniforge/base/envs/py_de/lib/python3.9/site-packages/deutschland/__init__.py)
```

My environment: 
- Mac 11.5.2. Big Sur, Python 3.9.6, pip 21.2.4, conda 4.10.3 (via Miniforge)

**Comment by auchtetraborat** [comment]
Similarly to #30, I have so far not been able to reproduce your issue in a fresh virtual environment. 

My environment: 
* Ubuntu 20.04, venv with 3.9.6 and pip 21.2.4

**Comment by darkBuddha** [comment]
I get the same message on macOS, also using miniforge.
