### ISSUE TITLE
No module named 'deutschland.geo'; 'deutschland' is not a package

### ISSUE THREAD

**Issue by ghattd** [bundesAPI/deutschland#71]
Hi,

trying to get your example `https://github.com/bundesAPI/deutschland#geographic-data` to run …

`pip3 install deutschland` on my macOS 12.5 with homebrew results in:
```
Requirement already satisfied: deutschland in /opt/homebrew/lib/python3.9/site-packages (0.1.4)
Requirement already satisfied: mapbox-vector-tile<2.0.0,>=1.2.1 in /opt/homebrew/lib/python3.9/site-packages (from deutschland) (1.2.1)
Requirement already satisfied: Shapely<2.0.0,>=1.7.1 in /opt/homebrew/lib/python3.9/site-packages (from deutschland) (1.8.2)
Requirement already satisfied: requests<3.0.0,>=2.26.0 in /opt/homebrew/lib/python3.9/site-packages (from deutschland) (2.28.1)
Requirement already satisfied: pyclipper in /opt/homebrew/lib/python3.9/site-packages (from mapbox-vector-tile<2.0.0,>=1.2.1->deutschland) (1.3.0.post3)
Requirement already satisfied: setuptools in /opt/homebrew/lib/python3.9/site-packages (from mapbox-vector-tile<2.0.0,>=1.2.1->deutschland) (63.3.0)
Requirement already satisfied: protobuf in /opt/homebrew/lib/python3.9/site-packages (from mapbox-vector-tile<2.0.0,>=1.2.1->deutschland) (4.21.4)
Requirement already satisfied: future in /opt/homebrew/lib/python3.9/site-packages (from mapbox-vector-tile<2.0.0,>=1.2.1->deutschland) (0.18.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.9/site-packages (from requests<3.0.0,>=2.26.0->deutschland) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.9/site-packages (from requests<3.0.0,>=2.26.0->deutschland) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.9/site-packages (from requests<3.0.0,>=2.26.0->deutschland) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/homebrew/lib/python3.9/site-packages (from requests<3.0.0,>=2.26.0->deutschland) (2.1.0)

[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python3.9 -m pip install --upgrade pip
```
(Didn’t save the initial output, but it seems to be successfully installed)

Now running your example code of `https://github.com/bundesAPI/deutschland#geographic-data` fails early in the game:
```
% python3 deutschland.py
Traceback (most recent call last):
  File "/Users/ghoffart/src/deutschland.py", line 1, in <module>
    from deutschland.geo import Geo
  File "/Users/ghoffart/src/deutschland.py", line 1, in <module>
    from deutschland.geo import Geo
ModuleNotFoundError: No module named 'deutschland.geo'; 'deutschland' is not a package
```
Am I overseeing something very obvious? Sorry, Python’s really not part of my knowledge package :-o

**Comment by wirthual** [comment]
Might be a problem with multiple python versions installed. 

Could [this](https://stackoverflow.com/questions/37341614/modules-are-installed-using-pip-on-osx-but-not-found-when-importing) help you?
